[tools]
cargo = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
lua = "5.1"
neovim = "latest"
node = "22"
"pipx:23andMe/Yamale" = "latest"
python = "3.12"
ripgrep = "latest"
ruff = "latest"
rust = "latest"
stylua = "latest"
